export const TaskTypes = {
  IMPORT_EPUB: 'IMPORT_EPUB',
  UPDATE_LIBRARY: 'UPDATE_LIBRARY',
  DRIVE_BACKUP: 'DRIVE_BACKUP',
  DRIVE_RESTORE: 'DRIVE_RESTORE',
  SELF_HOST_BACKUP: 'SELF_HOST_BACKUP',
  SELF_HOST_RESTORE: 'SELF_HOST_RESTORE',
  LOCAL_BACKUP: 'LOCAL_BACKUP',
  LOCAL_RESTORE: 'LOCAL_RESTORE',
  MIGRATE_NOVEL: 'MIGRATE_NOVEL',
  DOWNLOAD_CHAPTER: 'DOWNLOAD_CHAPTER',
  DOWNLOAD_NOVEL: 'DOWNLOAD_NOVEL',
  MASS_IMPORT: 'MASS_IMPORT',
  SYNC_FROM_TRACKERS: 'SYNC_FROM_TRACKERS',
  SYNC_TO_TRACKERS: 'SYNC_TO_TRACKERS',
  SYNC_ALL_TRACKERS: 'SYNC_ALL_TRACKERS',
  UPDATE_SELECTED: 'UPDATE_SELECTED',
  TTS: 'TTS',
  READING_SESSION: 'READING_SESSION',
} as const;

export type TaskType = (typeof TaskTypes)[keyof typeof TaskTypes];
