import { StyleSheet } from 'react-native';

export const trackModalStyles = StyleSheet.create({
  sharedDialogContainer: {
    marginVertical: '5%',
    marginHorizontal: 20,
    borderRadius: 32,
    maxHeight: '90%',
  },
  modalContainerLinking: {
    flex: 1,
    marginVertical: '5%',
    marginHorizontal: 20,
    borderRadius: 32,
    maxHeight: '90%',
  },
  modalContainerTracker: {
    flex: 1,
    marginVertical: '5%',
    marginHorizontal: 20,
    borderRadius: 32,
    maxHeight: '60%',
  },
  modalContent: { flex: 1 },
  appbarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    paddingHorizontal: 2,
    elevation: 0,
  },
  appbarTitle: { flex: 1, fontSize: 18, fontWeight: '500', marginLeft: 4 },
  searchContainer: { paddingHorizontal: 8, paddingVertical: 4 },
  readingListContainer: {
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  readingListLabel: { fontSize: 14, fontWeight: '500', marginBottom: 2 },
  readingListSelector: { flexDirection: 'row', alignItems: 'center' },
  refreshButton: { margin: 0 },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  loadingText: { marginTop: 8, fontSize: 16 },
  loadingMoreContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  loadingMoreText: { marginLeft: 8, fontSize: 14 },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  emptyText: { fontSize: 16, textAlign: 'center' },
  coverImage: { width: 48, height: 72, borderRadius: 4, margin: 8 },
  trackActions: { flexDirection: 'row', alignItems: 'center' },
  actionIconSpacing: { marginLeft: 8 },
  modalCancelButton: {
    marginTop: 8,
    paddingVertical: 8,
    borderRadius: 6,
    alignItems: 'center',
  },
  modalCancelText: { fontSize: 16, fontWeight: '600' },
  titlePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 8,
    marginTop: 4,
    borderWidth: 1,
    borderRadius: 8,
  },
  titlePickerText: { fontSize: 14, flex: 1 },
  pickerModalContainer: { margin: 20, borderRadius: 8 },
  pickerModalContent: { padding: 12 },
  pickerTitle: {
    fontSize: 18,
    fontWeight: '500',
    marginBottom: 12,
    textAlign: 'center',
  },
  pickerItemText: { fontSize: 16, paddingVertical: 8, paddingHorizontal: 12 },
  titleOption: { paddingVertical: 4, paddingHorizontal: 4, borderRadius: 4 },
  listOption: { paddingVertical: 4, paddingHorizontal: 4, borderRadius: 4 },
  linkingModalContainer: {
    margin: 20,
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowEndWithGap: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 12,
  },
  readingListLink: {
    marginTop: 4,
    textDecorationLine: 'underline',
    fontSize: 16,
  },
  searchResultItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 0.5,
  },
  searchResultContent: { flexDirection: 'row', alignItems: 'flex-start' },
  searchResultIcon: { marginRight: 12 },
  searchResultText: { flex: 1 },
  searchResultTitle: { fontSize: 16, fontWeight: '500', marginBottom: 4 },
  searchResultDescription: { fontSize: 14, lineHeight: 20 },
  webIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    marginTop: 2,
  },
  webIcon: { margin: 0, marginRight: 4 },
  webText: { fontSize: 14, fontWeight: '500' },
});

export type TrackModalStyles = typeof trackModalStyles;
